Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
src	+= Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Math', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
